Problem 4A Watermelon
Input w (1 <= w <= 100)

In [2]:
1 <= 3

true

In [7]:
4 / 2

2.0

In [19]:
# Print YES if the watermelon can be divided into two parts each weighing even number of
# kilos; print NO otherwise 
function watermelon_splitting(w::Int)
    y = w/2
    if iseven(y) === true
        return "YES"
    else 
        return "NO"
    end
end

watermelon_splitting (generic function with 1 method)

In [20]:
watermelon_splitting(4)

"YES"

In [21]:
watermelon_splitting(100)

"YES"

In [22]:
watermelon_splitting(101)

"NO"

Problem 71A Way Too Long Words
Word is too long if the length is > 10 characters.
If it's too long, replace with special abbreviation:
    - Take the first and last letter of the word
    - Count number of characters between first and last letter and insert that number between the first and last letter. 
  
e.g. localization -> l10n
internationalization -> i18n

In [23]:
x = "longword"

"longword"

In [24]:
length(x)

8

In [36]:
length(x) - 2

6

In [40]:
string(x[begin], length(x)-2, x[end])

"l6d"

In [45]:
function abbreviating_words(x::Int,words)
    for word in words
        if length(word) > 10
            a = string(word[begin], length(word)-2, word[end])
        println(a)
    else
        println(word)
        end
    end
end
        
        

abbreviating_words (generic function with 1 method)

In [43]:
wordlist = ["hello", "goodbye", "didworkohno"]

3-element Vector{String}:
 "hello"
 "goodbye"
 "didworkohno"

In [46]:
abbreviating_words(2, wordlist)

hello
goodbye
d9o


I've got the general idea but need to include the integer input 'x' as the number of lines 
of words

In [48]:
function abbreviating_words_2(x::Int,words)
    x = length(words)
    for i in x
        println(i)
    for word in words
        if length(word) > 10
            a = string(word[begin], length(word)-2, word[end])
        println(a)
    else
        println(word)
            end
        end
    end
end
        


abbreviating_words_2 (generic function with 1 method)

In [49]:
abbreviating_words_2(3, wordlist)

3
hello
goodbye
d9o


In [53]:
five_words = ["hi","bye","help","extrkakjlfdljalsdkfj","taasdfasdfaspestry"]

5-element Vector{String}:
 "hi"
 "bye"
 "help"
 "extrkakjlfdljalsdkfj"
 "taasdfasdfaspestry"

In [54]:
abbreviating_words_2(5, five_words)

5
hi
bye
help
e18j
t16y


Maybe I should remove 'x' as an argument and insert it as a process at the beginning of the function

In [57]:
function abbr_words(words)
    x = length(words)
    
    for i in x
        println(i)
        for word in words
            if length(word) > 10
                a = string(word[begin], length(word)-2, word[end])
        println(a)
    else
        println(word)
            end
        end
    end
end

abbr_words (generic function with 1 method)

In [58]:
abbr_words(five_words)

5
hi
bye
help
e18j
t16y


Problem 231A Team
First input line contains a single integer n (1 <= n <= 100), the number of problems in the contest.
Then n lines contain three integers each of 0 or 1. 
If the first number is 1 then petya knows the answer
If the second number is 1 then Vasya knows answer 
If the third number is 1 then Tonya knows answer 
They will solve a problem if *at least* two of them know the answer 

In [59]:
# Might start with an easy concrete example 
a = [ 1 1 0; 1 1 1; 1 0 0 ]

3×3 Matrix{Int64}:
 1  1  0
 1  1  1
 1  0  0

In [73]:
c = length(a[:,1])

3

In [80]:
# This was a bad approach; I don't need to store the outcome I need to determine the total
# number of outcomes that are greater than 2 i.e. how many problems can they solve
function teamwork(input_array)
    println(length(input_array[:,1]))
    y = []
    for i in input_array[:,1]
        if i === 1 
            push!(y, i)
        else
            for x in input_array[:,2]
                if x == 1
                    push!(y, x)
                else
                    for z in input_array[:,3]
                        if z == 1
                            push!(y, z)
                        end
                    end
                end
            end
        end
    end
end
            

teamwork (generic function with 1 method)

In [81]:
teamwork(a)

3


In [93]:
a

3×3 Matrix{Int64}:
 1  1  0
 1  1  1
 1  0  0

In [95]:
size(a,1) # 3 rows

3

In [96]:
size(a, 2)# 3 columns 

3

In [87]:
sum(a[1,:])

2

In [88]:
eachrow(a)

Base.Generator{Base.OneTo{Int64}, Base.var"#225#226"{Matrix{Int64}}}(Base.var"#225#226"{Matrix{Int64}}([1 1 0; 1 1 1; 1 0 0]), Base.OneTo(3))

In [89]:
?eachrow

search: eachrow searchsorted searchsortedlast searchsortedfirst



```
eachrow(A::AbstractVecOrMat)
```

Create a generator that iterates over the first dimension of vector or matrix `A`, returning the rows as `AbstractVector` views.

See also [`eachcol`](@ref), [`eachslice`](@ref), [`mapslices`](@ref).

!!! compat "Julia 1.1"
    This function requires at least Julia 1.1.


# Example

```jldoctest
julia> a = [1 2; 3 4]
2×2 Matrix{Int64}:
 1  2
 3  4

julia> first(eachrow(a))
2-element view(::Matrix{Int64}, 1, :) with eltype Int64:
 1
 2

julia> collect(eachrow(a))
2-element Vector{SubArray{Int64, 1, Matrix{Int64}, Tuple{Int64, Base.Slice{Base.OneTo{Int64}}}, true}}:
 [1, 2]
 [3, 4]
```


In [121]:
d = [ 1 2 3; 4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [128]:
println(sum(eachrow(d)))
sum(eachcol(d))

[5, 7, 9]


2-element Vector{Int64}:
  6
 15

In [108]:
6 >= 2

true

In [91]:
sum(eachcol(a))

3-element Vector{Int64}:
 2
 3
 1

In [119]:
function teamwork_again(arr)
    z = sum(eachcol(arr))
    println(count(i->(i>=2), z))
end

teamwork_again (generic function with 1 method)

In [120]:
teamwork_again(a) # They will attempt two of the problems  in a

2


In [129]:
# Trial input 
e = [1 1 0; 1 0 1; 1 1 1; 0 0 0; 0 1 1]

5×3 Matrix{Int64}:
 1  1  0
 1  0  1
 1  1  1
 0  0  0
 0  1  1

In [130]:
teamwork_again(e)

4
